### ISSUE TITLE
not working with polymer2 angular cli project

### ISSUE THREAD

**Issue by nishantgirbar** [ag-grid/ag-grid-polymer#3]
I was working on polymer4+polymer 2.0 (origami) project, in that project i am trying to integrate ag grid polymer but getting below error:

ERROR in ../src/assets/bower_compo
nents/ag-grid/src/ts/rendering/cellComp.ts (666,9): Type 'IComponent<any, IAfter
GuiAttachedParams>' is not assignable to type 'ICellRendererComp'.
  Property 'refresh' is missing in type 'IComponent<any, IAfterGuiAttachedParams
>'.

ERROR in ../src/assets/bower_compo
nents/ag-grid/src/ts/components/framework/namedComponentResolver.ts (25,13): Typ
e 'RegisteredComponent<IComponent<any, IAfterGuiAttachedParams>, {}>' is not ass
ignable to type 'RegisteredComponent<A, B>'.
  Type 'IComponent<any, IAfterGuiAttachedParams>' is not assignable to type 'A'.

ERROR in ../src/assets/bower_compo
nents/ag-grid/src/ts/components/framework/namedComponentResolver.ts (48,9): Type
 'ResolvedComponent<IComponent<any, IAfterGuiAttachedParams>, {}>' is not assign
able to type 'ResolvedComponent<A, B>'.
  Type 'IComponent<any, IAfterGuiAttachedParams>' is not assignable to type 'A'.

please help me sort out this issue.

Thanks,
Nishant Kumar

**Comment by seanlandsman** [comment]
As per the issue template, please don't post support queries here. Use either stackoverflow.com, or if you're an Enterprise customer you can also use our Members Forum here: https://ag-grid.com/forum/forumdisplay.php?fid=5
