### ISSUE TITLE
Possible bug, Date filter allows more than 4 digit in year

### ISSUE THREAD

**Issue by bmunnabe** [ag-grid/ag-grid-polymer#6]
Hi,

I am using Ag-grid polymer js version. In date filter it allows more than 4 digit. How should i prevent this fix this , is any property or api available or provided ? Documentation also not clear not able to find solution for this issue. Attached screenshot below

![image](https://user-images.githubusercontent.com/35695944/50205075-fb6c6300-038c-11e9-9d79-8cc23c2c9997.png)

**Comment by seanlandsman** [comment]
I'd suggest you create your own custom date component for something like this
