### ISSUE TITLE
NUMBER_PROPERTIES cant set any of them

### ISSUE THREAD

**Issue by reximus** [ag-grid/ag-grid-polymer#7]
Trying to set maxBlocksInCache value.
But it doesn't apply.

![image](https://user-images.githubusercontent.com/3177765/61310181-76e7a300-a7fc-11e9-818c-be1f41ae468a.png)
I guess NUMBER_PROPERTIES is missing.

**Comment by seanlandsman** [comment]
Hi

Thanks for reporting - this has been fixed and will be available in our next release (due out this week).

thanks
